name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  
jobs:
  build-and-push:
    name: Push Docker image to GitHub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - agent-provisioning
          - agent-service
          - api-gateway
          - cloud-wallet
          - connection
          - geolocation
          - issuance
          - ledger
          - notification
          - user
          - utility
          - verification
          - webhook
          - organization
          - seed
          - x509
          - oid4vc-issuance
          - oid4vc-verification

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git Tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfiles/Dockerfile.${{ matrix.service }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service }}:${{ env.TAG }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.service }}:latest